### PR TITLE
Upgrade to node-sass 6.0.1

### LINKED ISSUE #163: Cannot install because node-sass requires Python 2
```
$ npm install

> node-sass@4.13.1 install /home/frafra/Code/react-leaflet-markercluster/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.13.1 postinstall /home/frafra/Code/react-leaflet-markercluster/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/frafra/Code/react-leaflet-markercluster/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/frafra/Code/react-leaflet-markercluster/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.17.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/bin/python3" in the PATH
gyp verb `which` succeeded /usr/bin/python3 /usr/bin/python3
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:319:12)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Linux 5.13.8-200.fc34.x86_64
gyp ERR! command "/usr/bin/node" "/home/frafra/Code/react-leaflet-markercluster/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/frafra/Code/react-leaflet-markercluster/node_modules/node-sass
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN @egoist/vue-to-react@1.1.0 requires a peer of vue@^2.6.10 but none is installed. You must install peer dependencies yourself.
npm WARN leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN @react-leaflet/core@1.1.1 requires a peer of leaflet@^1.7.1 but none is installed. You must install peer dependencies yourself.
npm WARN @react-leaflet/core@1.1.1 requires a peer of react@^17.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN @react-leaflet/core@1.1.1 requires a peer of react-dom@^17.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-leaflet@3.2.2 requires a peer of leaflet@^1.7.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-leaflet@3.2.2 requires a peer of react@^17.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-leaflet@3.2.2 requires a peer of react-dom@^17.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/frafra/.npm/_logs/2021-10-24T14_58_40_990Z-debug.log
```

### PR DESCRIPTION
**Pull request by frafra**
Fix #163

Python 2 has reached EOL since the 1st of January 2020. It would be a good idea to upgrade node-sass to a more recent version.

### CODE REVIEW

**Comment by frafra** [comment]
Still relevant.

**Comment by frafra** [comment]
Still relevant.
Please disable this annoying and useless bot :D @yuzhva

**Comment by yuzhva** [comment]
`node-sass` been replaced with `sass` in `4.0.0-rc1` - thank to @charlieforward9 initiative to bring repo back to live

**Comment by charlieforward9** [comment]
I am currently working on a big dependency bump for ALL the dependencies with possible updates. This will probably take me another day to debug. @yuzhva

**Comment by charlieforward9** [comment]
This can be closed @yuzhva

**Pull request closed without merging**
