### PR TITLE
Fixing compatibility issue with leaflet v4 and React 18

### PR DESCRIPTION
**Pull request by changey**
Thanks to @l4b4r4b4b4 's work . This is to fix the compatibility issue with leaflet v4 and React 18 . @yuzhva @CodeCutterUK @webcarrot

### CODE REVIEW

**Comment by Lowentwickler** [comment]
Looking forward to have this merged

**Comment by Lowentwickler** [comment]
I have one issue with this on mobile. I also use popups. Once you click on a marker, the popup appears for a second and then disappears.

**Comment by barbalex** [comment]
https://github.com/changey/react-leaflet-markercluster works fine for me. Please merge this

**Comment by barbalex** [comment]
This is still relevant

**Comment by huraji** [comment]
Guys can we please merge this?

**Comment by Xelsaid** [comment]
Please guys, merge this pull request.

**Comment by l4b4r4b4b4** [comment]
well I think the original maintiner has gone under or dropped this project, since he shows activity for the 4th of August. So in then end the only solution would be to make a new release on npm.

Although to be honest with the code and my comments provided it all works like a charm :smiley_cat:

**Comment by charlieforward9** [comment]
Hello! I have recently gotten in touch with the original developer and have gained admin access to this repository. I would like to confirm that this branch is still good to be merged?

@changey @l4b4r4b4b4

**Comment by l4b4r4b4b4** [comment]
> Hello! I have recently gotten in touch with the original developer and have gained admin access to this repository. I would like to confirm that this branch is still good to be merged and released?
> 
> @changey @l4b4r4b4b4

:man_shrugging: dunnno tbh. Its been to long. Maybe just give it a try and write some test on top...

**Comment by barbalex** [comment]
I am still using https://github.com/changey/react-leaflet-markercluster and that still works. So probably this change will still be valid?

**Comment by barbalex** [comment]
Version 4.1.1 seems to work for us. Thanks!

**Pull request merged**
