### PR TITLE
Allow additional data to be passed to markers

### PR DESCRIPTION
**Pull request by MartinSahlen**
See http://stackoverflow.com/a/28664277 for an explanation, just making sure that we can send additional data to the marker component.

### CODE REVIEW

**Comment by MartinSahlen** [comment]
Ah, it seems my pull request was squashed. Should have done that myself, now it seems all my previous commits are there.

**Comment by YUzhva** [comment]
Check the sound:

Here is official leaflet documentation: http://leafletjs.com/reference-1.0.3.html#marker

L.marker has a lot of options like: icon, title, alt...

If you would like to send some of that option that you found in the official doc, you could make it like that:
```javascript
// Init leaflet icon according to the official doc
var myIcon = L.icon({
    iconUrl: 'my-icon.png',
    iconSize: [38, 95],
    iconAnchor: [22, 94]
});

// Generate list of markers
const markersList = [
  {lat: x, lng: x, options: {title: 'Hello world, alt: 'some alt', icon: myIcon}}
];

// Pass markers to the MarkerClusterGroup
<MarkerClusterGroup
        markers={markers} />
```

You should use options key for marker options. That key should support all marker options from leaflet documentation.

**Comment by MartinSahlen** [comment]
Thanks for getting back so fast. However, I did look at all the options, and they will not allow me to send *data*, just options for how the markers will appear or behave. By data I mean any data that makes semantic meaning for my app. I need  the number on the cluster markers to not be just the number of markers within the cluster but a number calculated from data in the clustered markers. More specifically, I am displaying total number of visits to all locations (markers) in a given cluster. Currently, the lib does not allow me to set or get app-specific data from markers within a cluster. The marker data will be accessed in a custom `iconCreateFunction`: 

```js
var markers = L.markerClusterGroup({
    iconCreateFunction: function(cluster) {

        var markers = cluster.getAllChildren()
        
        // access additional data
         console.log(markers[0].additionalData.myVariable);

        return L.divIcon({ html: '<b>' + cluster.getChildCount() + '</b>' });
    }
});
```

**Comment by YUzhva** [comment]
@MartinSahlen 

What do you think about events like:
```javascript
<MarkerClusterGroup
        markers={markers}
        onMarterClick={(marker) => console.log(marker)}
        onClusterClick={(cluster) => console.log(cluster.getChildCount())}
/>
```

That is just event listeners from:
https://github.com/Leaflet/Leaflet.markercluster#events

**Pull request closed without merging**
